INSERT INTO public.place (
  name,
  category,
  lat,
  lon,
  address,
  display_location,
  halal_status,
  serves_alcohol,
  source,
  external_id,
  status,
  google_place_id,
  google_match_status,
  google_match_score,
  google_match_method,
  google_business_status,
  google_maps_url
) VALUES (
  'Adel''s Famous Halal Food',
  'restaurant',
  40.7591946,
  -73.9811521,
  '1221 6th Ave, New York, NY 10020',
  'Midtown, Manhattan',
  'only',
  false,
  'manual',
  'manual:adels-famous-halal-food-nyc',
  'published',
  'ChIJNRe1Mf9YwokRvxBdos5UEY4',
  'matched',
  10,
  'text',
  'OPERATIONAL',
  'https://www.google.com/maps/place/?q=place_id:ChIJNRe1Mf9YwokRvxBdos5UEY4'
)
ON CONFLICT (source, external_id) DO UPDATE SET
  name = EXCLUDED.name,
  lat = EXCLUDED.lat,
  lon = EXCLUDED.lon,
  address = EXCLUDED.address,
  display_location = EXCLUDED.display_location,
  halal_status = EXCLUDED.halal_status,
  serves_alcohol = EXCLUDED.serves_alcohol,
  google_place_id = EXCLUDED.google_place_id,
  google_match_status = EXCLUDED.google_match_status,
  google_business_status = EXCLUDED.google_business_status,
  google_maps_url = EXCLUDED.google_maps_url;
